---
# tasks file for prometheus-role


- name: Update packages
  yum:
    name: '*'
    state: latest

- name: Install python3
  yum:
    name: python3
    state: present

- name: Install python3-pip
  yum:
    name: python3-pip
    state: present
      
- name: Pull tar repo from github
  ansible.builtin.unarchive:
    src: https://github.com/FSTEKbdit/prometheus-task/archive/refs/heads/main.tar.gz
    dest: /opt
    remote_src: yes

- name: Install python requirement
  ansible.builtin.pip:
    requirements: /opt/prometheus-task-main/requirements.txt
      
- name: Move Prometheus unit file
  command: mv /opt/prometheus-task-main/prometheus.service /lib/systemd/system/prometheus.service

- name: Start prometheus
  service:
    name: prometheus.service
    state: started
    enabled: yes
